### ISSUE TITLE
organize basic and token examples

### ISSUE THREAD

**Issue by shaj13** [shaj13/go-guardian#104]
### What did you expect to see?
token and basic example 

### What did you see instead?
https://github.com/shaj13/go-guardian/tree/master/_examples/basic_bearer

### TODO
split the basic_bearer to basic and token.
the token example can use the basic similar to  [jwt example](https://github.com/shaj13/go-guardian/blob/master/_examples/jwt/main.go)

**Comment by briwagner** [comment]
I took a shot at making a PR for this. I don't see it linked here, so maybe I missed something.

The basic example seemed pretty straight-forward.

Two things on the token example:
1. I added the `auth.RequestWithUser()` piece which I saw on another example. Seems to fit here.
2. I wondered about the curl example on line 27, using basic auth to access the record. I'm not sure if that is a bit outside the scope for token example. Seems more complicated to disallow that. 

Please let me know if this will work, or anything I can fix. Thanks for the opportunity

**Comment by shaj13** [comment]
@briwagner thx, PR merged, FYI, token-based authentication relay on pre-existing user credentials or a static token.

**Comment by shaj13** [comment]
FIXED #108
