### ISSUE TITLE
feature request: redis as a cache

### ISSUE THREAD

**Issue by c-nv-s** [shaj13/go-guardian#120]
### What version of Go-Guardian are you using ?
Go-Guardian Version: 2.11.4

It would be nice to be able to use redis as a cache for the store instead of in-memory.
This would allow more flexibility for scaling to multiple instances and help with app upgrades.

**Comment by shaj13** [comment]
@c-nv-s 

this is out of the scope of this library, 

* there are too many services out there that support caching like Memcached, redis etc. Introducing those caching layers will tremendously increase the library size and the maintenance effort. 

* auth caching should be locally to avoid network latency and for performance purposes.

See the following [tutorial](https://medium.com/@hajsanad/writing-scalable-authentication-in-golang-using-go-guardian-83691219a73a) on how to scale the app horizontally without relying on any third service.
