### ISSUE TITLE
Is cache implementation thread-safe?

### ISSUE THREAD

**Issue by amorey** [shaj13/go-guardian#124]
I noticed that shaj13/libcache's documentation says that lru.New() initializes a non-thread safe cache (https://github.com/shaj13/libcache/blob/master/lru/lru.go#L15) and I couldn't find any code to handle thread safety in go-guardian so I'm wondering, is go-guardian thread-safe? Can it be used in the request path of a go web server safely?

**Comment by shaj13** [comment]
@amorey thank you for reaching out, shaj13/libcache's and go-guardian, are operate completely independently.

go-guradian does not implement the underlying cache it only exposes an [interface](https://pkg.go.dev/github.com/shaj13/go-guardian/v2@v2.11.5/auth#Cache) so the user can write their own implementation or use libcache. 

However, go-guradian and libcache threaded safe and it's already running in production.

Regarding your question, all subpackage (lru, mru, etc..) initializes a non-thread safe, but the parent pkg offers a safe thread cache [see example](https://github.com/shaj13/libcache#thread-safe) so the user can choose a safe cache or unsafe cache.
