### ISSUE TITLE
Digest Example doesn't work on Chrome or FF

### ISSUE THREAD

**Issue by dhubler** [shaj13/go-guardian#84]
Chrome returns "MD5" as algorithm, not "md5" and you get error

     send error strategies/digest: algorithm Does not match value in provided header 

Workaround:

	alg := digest.SetHash(crypto.MD5, "MD5")
	strategy = digest.New(validateUser, c, alg)

**Comment by shaj13** [comment]
@dhubler good catch, thank you for reporting

**Comment by shaj13** [comment]
@dhubler  to get the fixe upgrade to v2.11.1
