### ISSUE TITLE
jwt Example doens't return a token

### ISSUE THREAD

**Issue by shachardevops** [shaj13/go-guardian#99]
### What version of Go are you using (`go version`)?

1.13
### Does this issue reproduce with the latest release?
yes

### What version of Go-Guardian are you using?

latest
### What did you do?
https://play.golang.org/p/NlbR34g1GRM
I just ran the jwt example 

### What did you expect to see?
I expect to get a token in the response 

### What did you see instead?
```
token:  
➜  ~ curl  -k http://127.0.0.1:8080/v1/book/1449311601 -u admin:admin
Author: Ryan Boyd 
➜  ~ curl  -k http://127.0.0.1:8080/v1/auth/token -u admin:admin
token:  
➜  ~ 
```
Token is empty

**Comment by shachardevops** [comment]
Solved - you need to update the example .  
replace ```		Method: gojwt.SigningMethodHS256,```
with ```		Algorithm: jwt.HS256,```

**Comment by shachardevops** [comment]
You did a really good job here! Awesome project.

**Comment by shaj13** [comment]
@shachardevops  thx,  I would love to see a PR.
